"""update

Revision ID: 116033894a52
Revises: 352fb4d535a2
Create Date: 2024-07-27 06:54:53.025537

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "116033894a52"
down_revision: Union[str, None] = "352fb4d535a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "cardroomuserlinktable_room_user_id_fkey",
        "cardroomuserlinktable",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "cardroomuserlinktable",
        "roomuser",
        ["room_user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "cardroomuserlinktable", type_="foreignkey")
    op.create_foreign_key(
        "cardroomuserlinktable_room_user_id_fkey",
        "cardroomuserlinktable",
        "roomuser",
        ["room_user_id"],
        ["id"],
    )
    # ### end Alembic commands ###
