"""Update

Revision ID: 352fb4d535a2
Revises: 35ea5b6f2d05
Create Date: 2024-07-27 06:38:37.056681

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "352fb4d535a2"
down_revision: Union[str, None] = "35ea5b6f2d05"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("roomuser", "room_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_constraint("roomuser_room_id_fkey", "roomuser", type_="foreignkey")
    op.create_foreign_key(
        None, "roomuser", "room", ["room_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "roomuser", type_="foreignkey")
    op.create_foreign_key(
        "roomuser_room_id_fkey", "roomuser", "room", ["room_id"], ["id"]
    )
    op.alter_column("roomuser", "room_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
