"""add_link_tables

Revision ID: 35ea5b6f2d05
Revises: 0e4dbed5d7ea
Create Date: 2024-07-24 14:11:15.536456

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "35ea5b6f2d05"
down_revision: Union[str, None] = "0e4dbed5d7ea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cardcardboxlinktable",
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column("cardbox_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["card.id"],
        ),
        sa.ForeignKeyConstraint(
            ["cardbox_id"],
            ["cardbox.id"],
        ),
        sa.PrimaryKeyConstraint("card_id", "cardbox_id"),
    )
    op.create_table(
        "cardroomuserlinktable",
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column("room_user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["card.id"],
        ),
        sa.ForeignKeyConstraint(
            ["room_user_id"],
            ["roomuser.id"],
        ),
        sa.PrimaryKeyConstraint("card_id", "room_user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cardroomuserlinktable")
    op.drop_table("cardcardboxlinktable")
    # ### end Alembic commands ###
